spring.application.name=harmonyhub-backend
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true

spring.graphql.websocket.path=

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=harmomyhub205@gmail.com
spring.mail.password=yknnmszxhgbyrven
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

server.address=0.0.0.0

spring.datasource.hikari.data-source-properties.sslmode=require

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=harmony123
server.ssl.key-alias=harmonyhub
server.ssl.enabled=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dymhzrzw7}
cloudinary.api-key=${CLOUDINARY_API_KEY:151324387452822}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Pn5MhOa6i-G4YgRRXWKw9ToYgWg}